language: generic
env:
  - HUGO_VERSION=0.36
addons:
  apt:
    packages:
    - python-pygments
before_script:
  - curl --silent -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar zxf -
script:
  - ./hugo
after_success:
  - echo "kawindi.com" >> public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
branch: develop