baseURL = "https://kawindi.com/"
languageCode = "en-us"
title = "Kawindi Muthukuda"
theme = "hugo-freelancer-theme"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Kawindi Muthukuda"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "kwmuth@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Kawindi Muthukuda's Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Kawindi Muthukuda"
        subtitle = "Electrical Engineer | Software Developer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About Me"
        # The about text is splitted into a left and right column
        left = "Hello! I'm Kawindi and this is my website. Here you can find a collection of all the projects that I've worked on, or are currently in the works - both work related and personal. <br> <br> I graduated with my bachelor's degree in electrical engineering from the University of British Columbia (UBC) in May 2017. Since then, I've been working for MDA, a space technology company, as a software developer. My current work contributes to the development and deployment of ground systems for Earth observation satellites."
	right = "Because I focused my degree on electrical engineering while gaining industry experience in software development, I have a good balance of both hardware and software knowledge. It has also engrained in me the mathematical rigour that is sometimes necessary to discover a less obvious but more elegant solution. <br> <br> I love tackling challenging problems and try to approach problem solving from an organized and methodical perspective. I feel that it has allowed me to achieve a deeper level of understanding of the task and, ultimately, the end goal. <br> <br> Thanks for stopping by. If you would like, feel free to connect with me on LinkedIn or send me an email."

        [params.about.button]
            text = "Download Resume"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Kawindi Muthukuda"

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Vancouver, Canada"]

        [params.footer.social]
            title = "Connect"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link = "https://www.linkedin.com/in/kawindimuthukuda/"

            #[[params.footer.social.networks]]
                #icon = "fa-github"
                #link=  "//stackoverflow.com/questions/tagged/hugo"


        #[params.footer.credits]
            #title = "About Kawindi"
            #text = "TEST"