name: Build Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
          submodules: recursive

      - name: Configure GIT_COMMIT_SHA env
        run: export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`

      - name: Configure GIT_COMMIT_SHA_SHORT env
        run: export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.64.0'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Add CNAME
        run: echo "kawindi.com" >> public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public

      - name: Purge Cloudflare CDN Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
