name: Build Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
          submodules: recursive

      - name: Configure GIT_COMMIT_SHA env
        run: export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`

      - name: Configure GIT_COMMIT_SHA_SHORT env
        run: export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.64.0'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Add CNAME
        run: echo "kawindi.com" >> public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public

      - name: Purge Cloudflare CDN Cache
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
          -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}" \
          -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_AUTH_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'